### ISSUE TITLE
User login behaves indeterministic and yields strange log statements

### ISSUE THREAD

**Issue by nbckr** [nbckr/speedy-recovery#20]
## Code version
Problem was identified in #18. In #19, I implemented a dirty hack.

## Description
I tried logging in as a patient. First, it worked, but I had suspicious console output:
<img src="https://user-images.githubusercontent.com/11090412/53307952-3d39ee00-3895-11e9-994c-10bbe49ac4b2.png" width="300" />

Then I tried it a second time and got this:
<img src="https://user-images.githubusercontent.com/11090412/53307957-504cbe00-3895-11e9-9b32-aa6b71068aa9.png" width="300" />

Third approach failed again. Fourth approach was successful, with same suspicious output.

**Comment by joshuazeltser** [comment]
I have fixed this issue and will push the changes to #18 PR. Basically, now that the mapAppointment function has two arguments you the way the map function was used to apply it to each member of the list of appointments wasn't working. This has now be fixed.
