### ISSUE TITLE
Synchronisation issue

### ISSUE THREAD

**Issue by nbckr** [nbckr/speedy-recovery#30]
## Description
I noticed a bug that happened often for me, but not always. 

![image](https://user-images.githubusercontent.com/11090412/53993947-b4d70b00-4128-11e9-8533-d5fc484d192e.png)

I have analysed the problem. It can be clearly read from the console output above: After the browser redirects from the sandbox back to SR, it is possible that the `user` info arrives before the `CapabilityStatement`. Then, the mapping fails, as it doesn't know which FHIR version to take, so the mapped user is `undefined`. The callback that's triggered (`handleLoginSuccess`) then fails when it tries to access `user.role`.

This is a non-deterministic issue and kind of related to my suspicions to what caused #20. @joshuazeltser your changes solved the other problem, but it seems there was a synchronisation issue after all.

## How to fix?
Dirty: add a default, fall-back FHIR version (3)
Clean: Implement a mechanism that makes sure all required data is ready before running the callbacks.

## Where did it occurr?
I first noticed in Kawai's home-page branch, but it also happens in `dev`.

**Comment by joshuazeltser** [comment]
I'm not able to reproduce this error on dev. I've tried lots of times and there are no issues?

**Comment by nbckr** [comment]
It is strange that you can't reproduce, but the issue does come up for me and Fabiha. Also, it totally makes sense. We do not take any precautions. How would we guarantee that the FHIR version is known before the Smart authenticated user is returned? These are two independent, asynchronous calls.

**Comment by nbckr** [comment]
Actually, did you have your console open, @joshuazeltser ? If you don't, this error is masked, because the WelcomeBox will still render

**Comment by nbckr** [comment]
Resolved with #32
